apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::129339633208:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-dbvYuBwxqsbz
      username: system:node:{{EC2PrivateDNSName}}
      - system:masters
      rolearn: arn:aws:iam::129339633208:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2025-05-27T02:01:14Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "4682"
  uid: e33c3b54-4a82-499a-a7ed-954a06edcfe9
